package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"backend/graph/model"
	"context"
	"fmt"
	"time"

	"golang.org/x/crypto/bcrypt"
)

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, input model.SignInInput) (*model.AuthPayload, error) {
	var id string
	var emailNull, usernameNull *string
	var passwordHash, dbRole string
	var createdAt time.Time

	err := r.DB.QueryRow(ctx,
		"SELECT id, email, username, password_hash, role, created_at FROM users WHERE email = $1",
		input.Email,
	).Scan(&id, &emailNull, &usernameNull, &passwordHash, &dbRole, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	if err := bcrypt.CompareHashAndPassword([]byte(passwordHash), []byte(input.Password)); err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	return &model.AuthPayload{
		User: &model.User{
			ID:        id,
			Email:     emailNull,
			Username:  usernameNull,
			Role:      roleFromDB(dbRole),
			CreatedAt: createdAt.Format(time.RFC3339),
		},
	}, nil
}

// CreateContactSubmission is the resolver for the createContactSubmission field.
func (r *mutationResolver) CreateContactSubmission(ctx context.Context, input model.CreateContactSubmissionInput) (*model.ContactSubmission, error) {
	panic(fmt.Errorf("not implemented: CreateContactSubmission - createContactSubmission"))
}

// MarkContactSubmissionRead is the resolver for the markContactSubmissionRead field.
func (r *mutationResolver) MarkContactSubmissionRead(ctx context.Context, id string, readerUserID string) (*model.ContactSubmission, error) {
	panic(fmt.Errorf("not implemented: MarkContactSubmissionRead - markContactSubmissionRead"))
}

// MarkContactSubmissionUnread is the resolver for the markContactSubmissionUnread field.
func (r *mutationResolver) MarkContactSubmissionUnread(ctx context.Context, id string) (*model.ContactSubmission, error) {
	panic(fmt.Errorf("not implemented: MarkContactSubmissionUnread - markContactSubmissionUnread"))
}

// AddContactSubmissionNote is the resolver for the addContactSubmissionNote field.
func (r *mutationResolver) AddContactSubmissionNote(ctx context.Context, input model.AddContactSubmissionNoteInput) (*model.ContactSubmissionNote, error) {
	panic(fmt.Errorf("not implemented: AddContactSubmissionNote - addContactSubmissionNote"))
}

// ArchiveContactSubmission is the resolver for the archiveContactSubmission field.
func (r *mutationResolver) ArchiveContactSubmission(ctx context.Context, id string, archived bool) (*model.ContactSubmission, error) {
	_, err := r.DB.Exec(ctx,
		`UPDATE contact_submissions SET archived = $1, updated_at = NOW() WHERE id = $2`,
		archived, id,
	)
	if err != nil {
		return nil, fmt.Errorf("archive contact submission: %w", err)
	}

	return r.getContactSubmissionByID(ctx, id, true)
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.CreateEventInput) (*model.Event, error) {
	var id string
	var createdAt time.Time
	err := r.DB.QueryRow(ctx,
		`INSERT INTO events (title, description, date, location, time, facebook_url, image_url)
		 VALUES ($1,$2,$3,$4,$5,$6,$7)
		 RETURNING id, created_at`,
		input.Title, input.Description, input.Date, input.Location,
		input.Time, input.FacebookURL, input.ImageURL,
	).Scan(&id, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("create event: %w", err)
	}
	return &model.Event{
		ID:          id,
		Title:       input.Title,
		Description: input.Description,
		Date:        input.Date,
		Location:    input.Location,
		Time:        input.Time,
		FacebookURL: input.FacebookURL,
		ImageURL:    input.ImageURL,
		CreatedAt:   createdAt.Format(time.RFC3339),
	}, nil
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id string, input model.UpdateEventInput) (*model.Event, error) {
	row := r.DB.QueryRow(ctx,
		`UPDATE events SET
		   title        = COALESCE($1, title),
		   description  = COALESCE($2, description),
		   date         = COALESCE($3::date, date),
		   location     = COALESCE($4, location),
		   time         = COALESCE($5, time),
		   facebook_url = COALESCE($6, facebook_url),
		   image_url    = COALESCE($7, image_url),
		   updated_at   = NOW()
		 WHERE id = $8
		 RETURNING id, title, description, date, location, time, facebook_url, image_url, created_at`,
		input.Title, input.Description, input.Date, input.Location,
		input.Time, input.FacebookURL, input.ImageURL, id,
	)
	return scanEvent(row)
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, id string) (bool, error) {
	tag, err := r.DB.Exec(ctx, "DELETE FROM events WHERE id = $1", id)
	if err != nil {
		return false, fmt.Errorf("delete event: %w", err)
	}
	return tag.RowsAffected() > 0, nil
}

// CreatePartner is the resolver for the createPartner field.
func (r *mutationResolver) CreatePartner(ctx context.Context, input model.CreatePartnerInput) (*model.Partner, error) {
	var id string
	err := r.DB.QueryRow(ctx,
		`INSERT INTO partners (name, logo_url, website_url, description)
		 VALUES ($1,$2,$3,$4) RETURNING id`,
		input.Name, input.LogoURL, input.WebsiteURL, input.Description,
	).Scan(&id)
	if err != nil {
		return nil, fmt.Errorf("create partner: %w", err)
	}
	return &model.Partner{
		ID:          id,
		Name:        input.Name,
		LogoURL:     input.LogoURL,
		WebsiteURL:  input.WebsiteURL,
		Description: input.Description,
	}, nil
}

// UpdatePartner is the resolver for the updatePartner field.
func (r *mutationResolver) UpdatePartner(ctx context.Context, id string, input model.UpdatePartnerInput) (*model.Partner, error) {
	row := r.DB.QueryRow(ctx,
		`UPDATE partners SET
		   name        = COALESCE($1, name),
		   logo_url    = COALESCE($2, logo_url),
		   website_url = COALESCE($3, website_url),
		   description = COALESCE($4, description),
		   updated_at  = NOW()
		 WHERE id = $5
		 RETURNING id, name, logo_url, website_url, description`,
		input.Name, input.LogoURL, input.WebsiteURL, input.Description, id,
	)
	return scanPartner(row)
}

// DeletePartner is the resolver for the deletePartner field.
func (r *mutationResolver) DeletePartner(ctx context.Context, id string) (bool, error) {
	tag, err := r.DB.Exec(ctx, "DELETE FROM partners WHERE id = $1", id)
	if err != nil {
		return false, fmt.Errorf("delete partner: %w", err)
	}
	return tag.RowsAffected() > 0, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	plain := ""
	if input.Password != nil && *input.Password != "" {
		plain = *input.Password
	} else {
		plain = randomPassword(12)
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(plain), 12)
	if err != nil {
		return nil, fmt.Errorf("hash password: %w", err)
	}

	var id string
	var createdAt time.Time
	err = r.DB.QueryRow(ctx,
		`INSERT INTO users (email, username, password_hash, role)
		 VALUES ($1,$2,$3,$4) RETURNING id, created_at`,
		input.Email, input.Username, string(hash), roleToDB(input.Role),
	).Scan(&id, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("create user: %w", err)
	}

	return &model.User{
		ID:        id,
		Email:     input.Email,
		Username:  input.Username,
		Role:      input.Role,
		CreatedAt: createdAt.Format(time.RFC3339),
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	var newHashPtr *string
	if input.Password != nil && *input.Password != "" {
		h, err := bcrypt.GenerateFromPassword([]byte(*input.Password), 12)
		if err != nil {
			return nil, fmt.Errorf("hash password: %w", err)
		}
		s := string(h)
		newHashPtr = &s
	}

	var roleStr *string
	if input.Role != nil {
		s := roleToDB(*input.Role)
		roleStr = &s
	}

	row := r.DB.QueryRow(ctx,
		`UPDATE users SET
		   email         = COALESCE($1, email),
		   username      = COALESCE($2, username),
		   role          = COALESCE($3::user_role, role),
		   password_hash = COALESCE($4, password_hash),
		   updated_at    = NOW()
		 WHERE id = $5
		 RETURNING id, email, username, role, created_at`,
		input.Email, input.Username, roleStr, newHashPtr, id,
	)
	return scanUser(row)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	tag, err := r.DB.Exec(ctx, "DELETE FROM users WHERE id = $1", id)
	if err != nil {
		return false, fmt.Errorf("delete user: %w", err)
	}
	return tag.RowsAffected() > 0, nil
}

// ResetUserPassword is the resolver for the resetUserPassword field.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, id string) (string, error) {
	plain := randomPassword(12)
	hash, err := bcrypt.GenerateFromPassword([]byte(plain), 12)
	if err != nil {
		return "", fmt.Errorf("hash password: %w", err)
	}
	_, err = r.DB.Exec(ctx,
		"UPDATE users SET password_hash = $1, updated_at = NOW() WHERE id = $2",
		string(hash), id,
	)
	if err != nil {
		return "", fmt.Errorf("reset password: %w", err)
	}
	return plain, nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context) ([]*model.Event, error) {
	rows, err := r.DB.Query(ctx,
		`SELECT id, title, description, date, location, time, facebook_url, image_url, created_at
		 FROM events ORDER BY date DESC`)
	if err != nil {
		return nil, fmt.Errorf("list events: %w", err)
	}
	defer rows.Close()

	var events []*model.Event
	for rows.Next() {
		e, err := scanEventRow(rows)
		if err != nil {
			return nil, err
		}
		events = append(events, e)
	}
	return events, nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*model.Event, error) {
	row := r.DB.QueryRow(ctx,
		`SELECT id, title, description, date, location, time, facebook_url, image_url, created_at
		 FROM events WHERE id = $1`, id)
	return scanEvent(row)
}

// Partners is the resolver for the partners field.
func (r *queryResolver) Partners(ctx context.Context) ([]*model.Partner, error) {
	rows, err := r.DB.Query(ctx,
		`SELECT id, name, logo_url, website_url, description FROM partners ORDER BY name`)
	if err != nil {
		return nil, fmt.Errorf("list partners: %w", err)
	}
	defer rows.Close()

	var partners []*model.Partner
	for rows.Next() {
		p, err := scanPartnerRow(rows)
		if err != nil {
			return nil, err
		}
		partners = append(partners, p)
	}
	return partners, nil
}

// Partner is the resolver for the partner field.
func (r *queryResolver) Partner(ctx context.Context, id string) (*model.Partner, error) {
	row := r.DB.QueryRow(ctx,
		`SELECT id, name, logo_url, website_url, description FROM partners WHERE id = $1`, id)
	return scanPartner(row)
}

// ContactSubmissions is the resolver for the contactSubmissions field.
func (r *queryResolver) ContactSubmissions(ctx context.Context, archived *bool) ([]*model.ContactSubmission, error) {
	a := false
	if archived != nil {
		a = *archived
	}

	rows, err := r.DB.Query(ctx,
		`SELECT id, first_name, last_name, phone, message, is_read, read_at, read_by_user_id, archived, last_note_at, created_at, updated_at
		 FROM contact_submissions WHERE archived = $1 ORDER BY created_at DESC`,
		a,
	)
	if err != nil {
		return nil, fmt.Errorf("list contact submissions: %w", err)
	}
	defer rows.Close()

	var items []*model.ContactSubmission
	for rows.Next() {
		var item model.ContactSubmission
		var readAt *time.Time
		var readByUserID *string
		var createdAt, updatedAt time.Time
		var lastNoteAt *time.Time

		if err := rows.Scan(
			&item.ID,
			&item.FirstName,
			&item.LastName,
			&item.Phone,
			&item.Message,
			&item.IsRead,
			&readAt,
			&readByUserID,
			&item.Archived,
			&lastNoteAt,
			&createdAt,
			&updatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan contact submission: %w", err)
		}

		if readAt != nil {
			t := readAt.Format(time.RFC3339)
			item.ReadAt = &t
		}
		if readByUserID != nil {
			reader, err := r.getUserByID(ctx, *readByUserID)
			if err != nil {
				return nil, err
			}
			item.ReadBy = reader
		}

		item.CreatedAt = createdAt.Format(time.RFC3339)
		item.UpdatedAt = updatedAt.Format(time.RFC3339)
		if lastNoteAt != nil {
			s := lastNoteAt.Format(time.RFC3339)
			item.LastNoteAt = &s
		}
		item.Notes = []*model.ContactSubmissionNote{}

		items = append(items, &item)
	}

	return items, nil
}

// ContactSubmission is the resolver for the contactSubmission field.
func (r *queryResolver) ContactSubmission(ctx context.Context, id string) (*model.ContactSubmission, error) {
	return r.getContactSubmissionByID(ctx, id, true)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	rows, err := r.DB.Query(ctx,
		`SELECT id, email, username, role, created_at FROM users ORDER BY created_at`)
	if err != nil {
		return nil, fmt.Errorf("list users: %w", err)
	}
	defer rows.Close()

	var users []*model.User
	for rows.Next() {
		u, err := scanUserRow(rows)
		if err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	return users, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func roleFromDB(r string) model.Role {
	switch strings.ToLower(r) {
	case "admin":
		return model.RoleAdmin
	case "moderator":
		return model.RoleModerator
	default:
		return model.RoleEditor
	}
}
func roleToDB(r model.Role) string {
	return strings.ToLower(string(r))
}
const passwordCharset = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789"
func randomPassword(length int) string {
	b := make([]byte, length)
	for i := range b {
		b[i] = passwordCharset[rand.Intn(len(passwordCharset))]
	}
	return string(b)
}
type rowScanner interface {
	Scan(dest ...any) error
}
func scanEvent(row rowScanner) (*model.Event, error) {
	var e model.Event
	var date time.Time
	var createdAt time.Time
	if err := row.Scan(&e.ID, &e.Title, &e.Description, &date, &e.Location, &e.Time, &e.FacebookURL, &e.ImageURL, &createdAt); err != nil {
		return nil, fmt.Errorf("scan event: %w", err)
	}
	e.Date = date.Format("2006-01-02")
	e.CreatedAt = createdAt.Format(time.RFC3339)
	return &e, nil
}
type pgxRows interface {
	Scan(dest ...any) error
}
func scanEventRow(row pgxRows) (*model.Event, error) {
	return scanEvent(row)
}
func scanPartner(row rowScanner) (*model.Partner, error) {
	var p model.Partner
	if err := row.Scan(&p.ID, &p.Name, &p.LogoURL, &p.WebsiteURL, &p.Description); err != nil {
		return nil, fmt.Errorf("scan partner: %w", err)
	}
	return &p, nil
}
func scanPartnerRow(row pgxRows) (*model.Partner, error) {
	return scanPartner(row)
}
func scanUser(row rowScanner) (*model.User, error) {
	var u model.User
	var dbRole string
	var createdAt time.Time
	if err := row.Scan(&u.ID, &u.Email, &u.Username, &dbRole, &createdAt); err != nil {
		return nil, fmt.Errorf("scan user: %w", err)
	}
	u.Role = roleFromDB(dbRole)
	u.CreatedAt = createdAt.Format(time.RFC3339)
	return &u, nil
}
func scanUserRow(row pgxRows) (*model.User, error) {
	return scanUser(row)
}
*/
