// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AddContactSubmissionNoteInput struct {
	SubmissionID string `json:"submissionId"`
	AuthorUserID string `json:"authorUserId"`
	Note         string `json:"note"`
}

type AuthPayload struct {
	User *User `json:"user"`
}

type ContactSubmission struct {
	ID         string                   `json:"id"`
	FirstName  string                   `json:"firstName"`
	LastName   string                   `json:"lastName"`
	Phone      *string                  `json:"phone,omitempty"`
	Message    string                   `json:"message"`
	IsRead     bool                     `json:"isRead"`
	ReadAt     *string                  `json:"readAt,omitempty"`
	ReadBy     *User                    `json:"readBy,omitempty"`
	Archived   bool                     `json:"archived"`
	LastNoteAt *string                  `json:"lastNoteAt,omitempty"`
	Notes      []*ContactSubmissionNote `json:"notes"`
	CreatedAt  string                   `json:"createdAt"`
	UpdatedAt  string                   `json:"updatedAt"`
}

type ContactSubmissionNote struct {
	ID           string `json:"id"`
	SubmissionID string `json:"submissionId"`
	Note         string `json:"note"`
	Author       *User  `json:"author"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type CreateContactSubmissionInput struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Phone     *string `json:"phone,omitempty"`
	Message   string  `json:"message"`
}

type CreateEventInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Date        string  `json:"date"`
	Location    *string `json:"location,omitempty"`
	Time        *string `json:"time,omitempty"`
	FacebookURL *string `json:"facebookUrl,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
}

type CreateOfferBlockInput struct {
	Section    string   `json:"section"`
	BlockType  string   `json:"blockType"`
	Badge      *string  `json:"badge,omitempty"`
	Title      *string  `json:"title,omitempty"`
	Subtitle   *string  `json:"subtitle,omitempty"`
	Content    *string  `json:"content,omitempty"`
	Items      []string `json:"items,omitempty"`
	Highlight  *string  `json:"highlight,omitempty"`
	ImageURL   *string  `json:"imageUrl,omitempty"`
	ImageAlt   *string  `json:"imageAlt,omitempty"`
	CtaLabel   *string  `json:"ctaLabel,omitempty"`
	CtaHref    *string  `json:"ctaHref,omitempty"`
	IsFeatured *bool    `json:"isFeatured,omitempty"`
	Order      *int32   `json:"order,omitempty"`
}

type CreatePartnerInput struct {
	Name        string  `json:"name"`
	LogoURL     *string `json:"logoUrl,omitempty"`
	WebsiteURL  *string `json:"websiteUrl,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateUserInput struct {
	Email    *string `json:"email,omitempty"`
	Username *string `json:"username,omitempty"`
	Role     Role    `json:"role"`
	Password *string `json:"password,omitempty"`
}

type Event struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Date        string  `json:"date"`
	Location    *string `json:"location,omitempty"`
	Time        *string `json:"time,omitempty"`
	FacebookURL *string `json:"facebookUrl,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	CreatedAt   string  `json:"createdAt"`
}

type Mutation struct {
}

type OfferBlock struct {
	ID         string   `json:"id"`
	Section    string   `json:"section"`
	BlockType  string   `json:"blockType"`
	Badge      *string  `json:"badge,omitempty"`
	Title      *string  `json:"title,omitempty"`
	Subtitle   *string  `json:"subtitle,omitempty"`
	Content    *string  `json:"content,omitempty"`
	Items      []string `json:"items"`
	Highlight  *string  `json:"highlight,omitempty"`
	ImageURL   *string  `json:"imageUrl,omitempty"`
	ImageAlt   *string  `json:"imageAlt,omitempty"`
	CtaLabel   *string  `json:"ctaLabel,omitempty"`
	CtaHref    *string  `json:"ctaHref,omitempty"`
	IsFeatured bool     `json:"isFeatured"`
	Order      int32    `json:"order"`
	CreatedAt  string   `json:"createdAt"`
	UpdatedAt  string   `json:"updatedAt"`
}

type Partner struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	LogoURL     *string `json:"logoUrl,omitempty"`
	WebsiteURL  *string `json:"websiteUrl,omitempty"`
	Description *string `json:"description,omitempty"`
}

type Query struct {
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateEventInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Date        *string `json:"date,omitempty"`
	Location    *string `json:"location,omitempty"`
	Time        *string `json:"time,omitempty"`
	FacebookURL *string `json:"facebookUrl,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
}

type UpdateOfferBlockInput struct {
	Section    *string  `json:"section,omitempty"`
	BlockType  *string  `json:"blockType,omitempty"`
	Badge      *string  `json:"badge,omitempty"`
	Title      *string  `json:"title,omitempty"`
	Subtitle   *string  `json:"subtitle,omitempty"`
	Content    *string  `json:"content,omitempty"`
	Items      []string `json:"items,omitempty"`
	Highlight  *string  `json:"highlight,omitempty"`
	ImageURL   *string  `json:"imageUrl,omitempty"`
	ImageAlt   *string  `json:"imageAlt,omitempty"`
	CtaLabel   *string  `json:"ctaLabel,omitempty"`
	CtaHref    *string  `json:"ctaHref,omitempty"`
	IsFeatured *bool    `json:"isFeatured,omitempty"`
	Order      *int32   `json:"order,omitempty"`
}

type UpdatePartnerInput struct {
	Name        *string `json:"name,omitempty"`
	LogoURL     *string `json:"logoUrl,omitempty"`
	WebsiteURL  *string `json:"websiteUrl,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateUserInput struct {
	Email    *string `json:"email,omitempty"`
	Username *string `json:"username,omitempty"`
	Role     *Role   `json:"role,omitempty"`
	Password *string `json:"password,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Email     *string `json:"email,omitempty"`
	Username  *string `json:"username,omitempty"`
	Role      Role    `json:"role"`
	CreatedAt string  `json:"createdAt"`
}

type Role string

const (
	RoleAdmin     Role = "ADMIN"
	RoleModerator Role = "MODERATOR"
	RoleEditor    Role = "EDITOR"
	RoleOwner     Role = "OWNER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleModerator,
	RoleEditor,
	RoleOwner,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleModerator, RoleEditor, RoleOwner:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
